const ACCOUNT_ROUTE_PREFIX = '/account/v1/';
const ACCOUNT_SIGNUP_ROUTE = `/signup`;
const ACCOUNT_SIGNIN_ROUTE = `/signin`;

export {ACCOUNT_ROUTE_PREFIX, ACCOUNT_SIGNUP_ROUTE, ACCOUNT_SIGNIN_ROUTE};
